server.port: 8080

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/cars?useSSL=false
    username: root
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4